# Generated by Django 5.2 on 2026-06-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_user_alter_run_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='user',
        ),
    ]
