# Generated by Django 5.2 on 2026-06-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_remove_run_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='athlete',
        ),
    ]
